name: Auto Tweet Using AI

# Runs every hour
on:
  schedule:
    - cron: "0 * * * *"
  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    name: Auto Tweet Using AI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      
      - name: Install Dependencies
        run: npm i
        
      - name: Run Twitter bot
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm start
